name: Test And Report V2

on:
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: "ALLURE_JOB_RUN_ID service parameter. Leave blank."
        required: false
      ALLURE_USERNAME:
        description: "ALLURE_USERNAME service parameter. Leave blank"
        required: false

jobs:
  test-and-report:
    if: github.ref == 'refs/heads/full-allure-annotation'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e .

      - name: Install and configure allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: ${{ secrets.ALLURE_ENDPOINT }}
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: 10680
          
      - name: Run pytest tests with allurectl watcher
        run: | 
          allurectl watch -- pytest --alluredir=${ALLURE_RESULTS} || true
          printenv | grep "ALLURE\|GITHUB" > env.list
          export $( allurectl job-run env)
          printenv | grep TEST_
          printenv | grep ALLURE_
          echo "Now, printing what we have in env.list"
          cat env.list
        env:
          ALLURE_RESULTS: "allure-results"
          ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}  
